obj-m += lcd_test_mod_mei_me_vmfunc_mei_me_lcd.o

lcd_test_mod_mei_me_vmfunc_mei_me_lcd-y		+= main.o

# Original code
lcd_test_mod_mei_me_vmfunc_mei_me_lcd-y		+= hw-me.o pci-me.o 


lcd_test_mod_mei_me_vmfunc_mei_me_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_mei_me_vmfunc_mei_me_lcd-y		+= $(addprefix glue/, mei_caller.o \
						mei_caller_dispatch.o )

lcd_test_mod_mei_me_vmfunc_mei_me_lcd-y		+= $(addprefix ../, mei_glue_helper.o)

ccflags-y += $(ISOLATED_CFLAGS)

