obj-m += lcd_test_mod_nvme_vmfunc_blk_klcd.o

lcd_test_mod_nvme_vmfunc_blk_klcd-y		+= main.o

# glue code
lcd_test_mod_nvme_vmfunc_blk_klcd-y		+= $(addprefix glue/, nvme_callee.o \
						nvme_callee_dispatch.o )

						#ixgbe_xmit.o \

lcd_test_mod_nvme_vmfunc_blk_klcd-y		+= $(addprefix ../, nvme_cap.o)

cppflags-y += $(NONISOLATED_CFLAGS)

#extra-y += glue/nvme_callee.lds

#ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/ixgbe_vmfunc/blk_klcd/glue/nvme_callee.lds

ccflags-y += $(NONISOLATED_CFLAGS)
