
# VFS --------------------------------------------------

obj-m += lcd_test_mod_glue_example_vfs.o

# original code
lcd_test_mod_glue_example_vfs-y      += original/main.o

# if we're isolating ...

# link with liblcd
lcd_test_mod_glue_example_vfs-$(CONFIG_ISOLATE_GLUE_EXAMPLE) += ../$(LIBLCD)

# link with glue
lcd_test_mod_glue_example_vfs-$(CONFIG_ISOLATE_GLUE_EXAMPLE)  += glue/boot.o
lcd_test_mod_glue_example_vfs-$(CONFIG_ISOLATE_GLUE_EXAMPLE)  += glue/vfs_callee.o

# Run linker script through C preprocessor (so we can use macros)
cppflags-y := -I$(LCD_DOMAINS_INCLUDE)
extra-y := glue/vfs_callee.lds

# run link script
ldflags-$(CONFIG_ISOLATE_GLUE_EXAMPLE) += -T $(src)/glue/vfs_callee.lds
