obj-m += lcd_test_mod_ixgbe_ixgbe_lcd.o

lcd_test_mod_ixgbe_ixgbe_lcd-y		+= main.o

# Original code
lcd_test_mod_ixgbe_ixgbe_lcd-y		+= ixgbe_main.o


lcd_test_mod_ixgbe_ixgbe_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_ixgbe_ixgbe_lcd-y		+= $(addprefix glue/, ixgbe_caller.o \
						ixgbe_caller_dispatch.o )

lcd_test_mod_ixgbe_ixgbe_lcd-y		+= $(addprefix ../, ixgbe_cap.o)

ccflags-y += $(ISOLATED_CFLAGS)

