obj-m += lcd_test_mod_xhci_hcd_gen_xhci_hcd_lcd.o

lcd_test_mod_xhci_hcd_gen_xhci_hcd_lcd-y		+= main.o

# Original code
lcd_test_mod_xhci_hcd_gen_xhci_hcd_lcd-y		+= $(addprefix xhci-hcd/, xhci.o xhci-mem.o xhci-ring.o xhci-hub.o )


lcd_test_mod_xhci_hcd_gen_xhci_hcd_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_xhci_hcd_gen_xhci_hcd_lcd-y		+= $(addprefix ../, client.o common.o glue_user.o )

ccflags-y += $(ISOLATED_CFLAGS)

extra-y += ../../../liblcd_build/common/vmfunc.lds

ldflags-y += -T $(LIBLCD_BUILD_DIR)/common/vmfunc.lds

cppflags-y += $(ISOLATED_CFLAGS)

