/* 
 * syscall.h -- Syscall IDs
 *
 * Copyright: University of Utah
 */
#ifndef LCD_DOMAINS_SYSCALL_H
#define LCD_DOMAINS_SYSCALL_H

enum lcd_syscall {
	LCD_SYSCALL_EXIT,
	LCD_SYSCALL_PUTCHAR,
	LCD_SYSCALL_SEND,
	LCD_SYSCALL_RECV,
	LCD_SYSCALL_CALL,
	LCD_SYSCALL_REPLY,
	LCD_SYSCALL_CREATE_SYNC_EP,
	LCD_SYSCALL_PAGES_ALLOC_EXACT_NODE,
	LCD_SYSCALL_PAGES_ALLOC,
	LCD_SYSCALL_MMAP,
	LCD_SYSCALL_MUNMAP,
	LCD_SYSCALL_CAP_DELETE,
	LCD_SYSCALL_CAP_REVOKE,
};

#endif /* LCD_DOMAINS_SYSCALL_H */
