
obj-m  += lcd_test_mod_async_rpc_caller_lcd.o

lcd_test_mod_async_rpc_caller_lcd-y              += main.o

lcd_test_mod_async_rpc_caller_lcd-y              += $(LIBLCD)

ccflags-y += $(ISOLATED_CC_FLAGS)