#
# This file tells the kernel build system how to build our
# module.
#

obj-m += lcd_test_mod_llvm_example_lcd.o

lcd_test_mod_llvm_example_lcd-y      += lcd.o

# ISOLATED CONFIG --------------------------------------------------

lcd_test_mod_llvm_example_lcd-$(LCD_CONFIG_LLVM_EXAMPLE_LCD_ISOLATED) += \
	$(LIBLCD)
ccflags-$(LCD_CONFIG_LLVM_EXAMPLE_LCD_ISOLATED) += $(ISOLATED_CFLAGS)

# DEKER CONFIG --------------------------------------------------

ifneq ($(LCD_CONFIG_LLVM_EXAMPLE_LCD_DEKER),)
include $(DEKER_KBUILD_CONFIG)
endif

lcd_test_mod_llvm_example_lcd-$(LCD_CONFIG_LLVM_EXAMPLE_LCD_DEKER) += \
	environment.o
lcd_test_mod_llvm_example_lcd-$(LCD_CONFIG_LLVM_EXAMPLE_LCD_DEKER) += \
	$(LIBDEKER_RUNTIME)
lcd_test_mod_llvm_example_lcd-$(LCD_CONFIG_LLVM_EXAMPLE_LCD_DEKER) += \
	$(LIBDEKER)
ccflags-$(LCD_CONFIG_LLVM_EXAMPLE_LCD_DEKER) += $(DEKER_CFLAGS)
