obj-m += lcd_test_mod_ixgbe_gen_net_klcd.o

lcd_test_mod_ixgbe_gen_net_klcd-y		+= main.o

# glue code
lcd_test_mod_ixgbe_gen_net_klcd-y		+= $(addprefix ../, server.o common.o glue_user.o )

cppflags-y += $(NONISOLATED_CFLAGS)

extra-y += ../trampolines.lds

ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/ixgbe_gen/trampolines.lds

ccflags-y += $(NONISOLATED_CFLAGS)
