obj-m += lcd_test_mod_nullnet_idl_lcd.o

lcd_test_mod_nullnet_idl_lcd-y += nullnet_lcd.o
lcd_test_mod_nullnet_idl_lcd-y += ../common.o
lcd_test_mod_nullnet_idl_lcd-y += main.o
lcd_test_mod_nullnet_idl_lcd-y += dummy.o
lcd_test_mod_nullnet_idl_lcd-y += $(LIBLCD)

extra-y += trampolines.lds
extra-y += ../../../liblcd_build/common/vmfunc.lds

cppflags-y += $(ISOLATED_CFLAGS)
ccflags-y += $(ISOLATED_CFLAGS) -std=gnu99 -Wno-error=declaration-after-statement -Wno-error=discarded-qualifiers

ldflags-y += -T $(LIBLCD_BUILD_DIR)/common/vmfunc.lds
ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/nullnet_idl/klcd/trampolines.lds
