obj-m += lcd_test_mod_acpi_hwmon_vmfunc_pwmtr_lcd.o

lcd_test_mod_acpi_hwmon_vmfunc_pwmtr_lcd-y		+= main.o

# Original code
lcd_test_mod_acpi_hwmon_vmfunc_pwmtr_lcd-y		+= acpi_power_meter.o


lcd_test_mod_acpi_hwmon_vmfunc_pwmtr_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_acpi_hwmon_vmfunc_pwmtr_lcd-y		+= $(addprefix glue/, acpi_hwmon_caller.o \
									acpi_hwmon_caller_dispatch.o )

lcd_test_mod_acpi_hwmon_vmfunc_pwmtr_lcd-y		+= $(addprefix ../, acpi_hwmon_glue_helper.o)

ccflags-y += $(ISOLATED_CFLAGS)

extra-y += ../../../liblcd_build/common/vmfunc.lds

ldflags-y += -T $(LIBLCD_BUILD_DIR)/common/vmfunc.lds
