
# Main targets
obj-$(CONFIG_LCD_TEST_MOD_CREATE_KLCD_BOOT) += lcd-test-mod-create-klcd-boot.o

lcd-test-mod-create-klcd-boot-y             += boot.o

obj-$(CONFIG_LCD_TEST_MOD_CREATE_KLCD_KLCD) += lcd-test-mod-create-klcd-klcd.o

lcd-test-mod-create-klcd-klcd-y             += klcd.o

