
# Set this to y to build code for isolation (along with boot module).
# Set it to nothing to build code for normal operation.
export ISOLATE_GLUE_EXAMPLE=y

ifeq ($(ISOLATE_GLUE_EXAMPLE),y)

	obj-m += isol_boot/
	ISOLATED_CC_FLAGS += -DISOLATE_GLUE_EXAMPLE	

endif

obj-m += vfs/
obj-m += minix/