module kernel {

	rpc_ptr int ctr( projection ti [alloc(callee)] * ti, unsigned int argc, char** [unused] argv ) {
		projection < struct dm_target > ti {
			unsigned int [out] num_discard_bios;
			//string [alloc(caller), out] *error;
		}
	}

	rpc_ptr int map( projection ti * [unused] ti, projection bio [alloc(callee)] * bio ) {
		projection < struct dm_target > ti {
		}
		projection < struct bio > bio {
			unsigned int  bi_opf;
		}
	}

	rpc void zero_fill_bio( projection bio * bio ) {
		projection < struct bio > bio {
		}
	}

	rpc void bio_endio( projection bio * bio ) {
		projection < struct bio > bio {
		}
	}
	
	rpc void dm_unregister_target( projection tt [bind(callee)] * tt ) {
		projection < struct target_type > tt {
			const string [alloc(callee)] *name;
			array <unsigned int, 3> version;
			rpc_ptr ctr ctr;
			rpc_ptr map map;
		}
	}

	rpc int dm_register_target( projection tt [alloc(callee)] * tt ) {
		projection < struct target_type > tt {
			const string [alloc(callee)] *name;
			array <unsigned int, 3> version;
			rpc_ptr ctr ctr;
			rpc_ptr map map;
		}
	}


}
