#
# Modules for testing
#

# This should be built before entering this file (it will be
# if you use the top level makefile in lcd-domains/Makefile)
export LIBLCD = ../../liblcd/lib.a

obj-m += load/

obj-m += ipc1/

obj-m += ipc2/

obj-m += liblcd_tests/

obj-m += create_klcd/

obj-m += glue_example/

obj-m += pmfs/

obj-m += async/

obj-m += string_example/