obj-m += lcd_test_mod_ixgbe_gen_ixgbe_lcd.o

lcd_test_mod_ixgbe_gen_ixgbe_lcd-y		+= main.o

# Original code
lcd_test_mod_ixgbe_gen_ixgbe_lcd-y		+= $(addprefix ixgbe/, ixgbe_main.o ixgbe_ethtool.o ixgbe_lib.o ixgbe_common.o ixgbe_82599.o ixgbe_phy.o )  


lcd_test_mod_ixgbe_gen_ixgbe_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_ixgbe_gen_ixgbe_lcd-y		+= $(addprefix ../, client.o common.o glue_user.o )

ccflags-y += $(ISOLATED_CFLAGS)

extra-y += ../../../liblcd_build/common/vmfunc.lds

ldflags-y += -T $(LIBLCD_BUILD_DIR)/common/vmfunc.lds

cppflags-y += $(ISOLATED_CFLAGS)

