obj-$(CONFIG_LCD_PROTOTYPE_TEST_CUSTOMER)     += lcd-prototype-customer.o
lcd-prototype-test-customer-y                 += customer.o customer-idl.o

obj-$(CONFIG_LCD_PROTOTYPE_TEST_DEALER)       += lcd-prototype-dealer.o
lcd-prototype-test-dealer-y                   += dealer.o dealer-idl.o

obj-$(CONFIG_LCD_PROTOTYPE_TEST_MANUFACTURER) += lcd-prototype-manufacturer.o
lcd-prototype-test-manufacturer-y          += manufacturer.o manufacturer-idl.o

