obj-$(CONFIG_LCD_PROTOTYPE_TEST_BOOT)         += lcd-prototype-test-boot.o
lcd-prototype-test-boot-y                     += boot.o

obj-$(CONFIG_LCD_PROTOTYPE_TEST_CUSTOMER)     += lcd-prototype-test-customer.o
lcd-prototype-test-customer-y                 += customer.o customer-idl.o

obj-$(CONFIG_LCD_PROTOTYPE_TEST_DEALER)       += lcd-prototype-test-dealer.o
lcd-prototype-test-dealer-y                   += dealer.o dealer-idl.o

obj-$(CONFIG_LCD_PROTOTYPE_TEST_MANUFACTURER) += lcd-prototype-test-manufacturer.o
lcd-prototype-test-manufacturer-y          += manufacturer.o manufacturer-idl.o

