
ccflags-y += $(NONISOLATED_CFLAGS)
ccflags-y += -DOTHER_DOMAIN=1

obj-m  += lcd_test_mod_vmfunc_klcd_caller_klcd.o

lcd_test_mod_vmfunc_klcd_caller_klcd-y              += main.o
lcd_test_mod_vmfunc_klcd_caller_klcd-y              += $(addprefix ../, vmfunc.o vmfunc_wrapper.o)


extra-y += ../vmfunc.lds

ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/vmfunc_klcd/vmfunc.lds
