#
# Top-level test mods Kbuild file
#

include Kbuild.config

# Examples

obj-m += liblcd_test/
obj-m += load/
obj-m += ipc1/
obj-m += ipc2/
obj-m += async/
obj-m += create_klcd/
obj-m += glue_example/
obj-m += string_example/
obj-m += pmfs/
obj-m += bug/
obj-m += async_rpc/
