#
# Top-level test mods Kbuild file
#
# Some of these variables are exported from the top-level Makefile.
#

export ISOLATED_CC_FLAGS= $(LIBLCD_CFLAGS)

export NON_ISOLATED_CC_FLAGS= $(MICROKERNEL_CFLAGS)

# Examples

obj-m += liblcd_test/
obj-m += load/
obj-m += ipc1/
obj-m += ipc2/
obj-m += async/
obj-m += create_klcd/
obj-m += glue_example/
obj-m += string_example/
obj-m += pmfs/