obj-m += lcd_test_mod_nullnet_dummy_lcd.o

lcd_test_mod_nullnet_dummy_lcd-y		+= main.o

# Original code
lcd_test_mod_nullnet_dummy_lcd-y		+= dummy.o 


lcd_test_mod_nullnet_dummy_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_nullnet_dummy_lcd-y		+= $(addprefix glue/, nullnet_caller.o \
						dispatch.o )

lcd_test_mod_nullnet_dummy_lcd-y		+= $(addprefix ../, cap.o)

ccflags-y += $(ISOLATED_CFLAGS)

