obj-m += lcd_test_mod_ixgbe_vmfunc_net_klcd.o

lcd_test_mod_ixgbe_vmfunc_net_klcd-y		+= main.o

# glue code
lcd_test_mod_ixgbe_vmfunc_net_klcd-y		+= $(addprefix glue/, ixgbe_callee.o \
						ixgbe_callee_dispatch.o )

						#ixgbe_xmit.o \

lcd_test_mod_ixgbe_vmfunc_net_klcd-y		+= $(addprefix ../, ixgbe_cap.o)

cppflags-y += $(NONISOLATED_CFLAGS)

#extra-y += glue/ixgbe_callee.lds

#ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/ixgbe_vmfunc/net_klcd/glue/ixgbe_callee.lds

ccflags-y += $(NONISOLATED_CFLAGS)
