
# VFS --------------------------------------------------

obj-m += lcd_test_mod_glue_example_vfs.o

# original code
lcd_test_mod_glue_example_vfs-y      += original/main.o

LCD_VFS_BUILD_PATH = $(LCD_TEST_MODULES_BUILD_DIR)/glue_example/vfs

# if we're isolating ...
ifeq ($(ISOLATE_GLUE_EXAMPLE),y)

	# link with liblcd
	lcd_test_mod_glue_example_vfs-y += $(LIBLCD)

	# link with glue
	lcd_test_mod_glue_example_vfs-y += glue/boot.o
	lcd_test_mod_glue_example_vfs-y += glue/vfs_callee.o
	lcd_test_mod_glue_example_vfs-y += glue/vfs_cap.o

	ccflags-y += $(ISOLATED_CC_FLAGS)

	# Run linker script through C preprocessor (so we can use macros)
	cppflags-y := $(ISOLATED_CC_FLAGS)
	extra-y := glue/vfs_callee.lds

	# run link script
	ldflags-y += -T $(LCD_VFS_BUILD_PATH)/glue/vfs_callee.lds

else

	ccflags-y += $(NON_ISOLATED_CC_FLAGS)

endif
