
# Main targets
obj-m  += lcd_test_mod_ipc2_boot.o

lcd_test_mod_ipc2_boot-y              += boot.o

obj-m  += lcd_test_mod_ipc2_lcd1.o

lcd_test_mod_ipc2_lcd1-y              += lcd1.o

lcd_test_mod_ipc2_lcd1-y              += $(LIBLCD)

obj-m += lcd_test_mod_ipc2_lcd2.o

lcd_test_mod_ipc2_lcd2-y              += lcd2.o

lcd_test_mod_ipc2_lcd2-y              += $(LIBLCD)
