obj-m += lcd_test_mod_nullblk_gen_blk_klcd.o

lcd_test_mod_nullblk_gen_blk_klcd-y		+= main.o

lcd_test_mod_nullblk_gen_blk_klcd-y		+= $(addprefix ../, server.o common.o glue_user.o)

cppflags-y += $(NONISOLATED_CFLAGS)

extra-y += $(addprefix ../, trampolines.lds)

ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/nullblk_gen/trampolines.lds

ccflags-y += $(NONISOLATED_CFLAGS)
