
# Main targets
obj-m += lcd_test_mod_bug_boot.o

lcd_test_mod_bug_boot-y             += boot.o

obj-m  += lcd_test_mod_bug_lcd.o

lcd_test_mod_bug_lcd-y              += lcd.o

lcd_test_mod_bug_lcd-y              += $(LIBLCD)

# We don't want the loop to be optimized away
CFLAGS_lcd.o = -O0
