obj-m += lcd_test_mod_skx_edac_vmfunc_skx_edac_lcd.o

lcd_test_mod_skx_edac_vmfunc_skx_edac_lcd-y		+= main.o

# Original code
lcd_test_mod_skx_edac_vmfunc_skx_edac_lcd-y		+= 


lcd_test_mod_skx_edac_vmfunc_skx_edac_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_skx_edac_vmfunc_skx_edac_lcd-y		+= $(addprefix glue/, skx_edac_vmfunc_caller.o \
						skx_edac_vmfunc_caller_dispatch.o )

lcd_test_mod_skx_edac_vmfunc_skx_edac_lcd-y		+= $(addprefix ../, skx_edac_vmfunc_cap.o)

ccflags-y += $(ISOLATED_CFLAGS)

