obj-m += lcd_test_mod_msr_vmfunc_msr_lcd.o

lcd_test_mod_msr_vmfunc_msr_lcd-y		+= main.o

# Original code
lcd_test_mod_msr_vmfunc_msr_lcd-y		+= msr.o


lcd_test_mod_msr_vmfunc_msr_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_msr_vmfunc_msr_lcd-y		+= $(addprefix glue/, msr_caller.o \
						msr_caller_dispatch.o )

lcd_test_mod_msr_vmfunc_msr_lcd-y		+= $(addprefix ../, msr_glue_helper.o)

ccflags-y += $(ISOLATED_CFLAGS)

extra-y += ../../../liblcd_build/common/vmfunc.lds

ldflags-y += -T $(LIBLCD_BUILD_DIR)/common/vmfunc.lds
