
obj-m  += lcd_test_mod_async_rpc_callee_lcd.o

lcd_test_mod_async_rpc_callee_lcd-y              += main.o

lcd_test_mod_async_rpc_callee_lcd-y              += $(LIBLCD)

ccflags-y += $(ISOLATED_CC_FLAGS)