#
# Top-level test mods Kbuild file
#
# A lot of variables are set in the top-level Makefile, and in
# scripts/Makefile.test_mods. In addition, some of the Kbuild files
# are preprocessed to add/redefine some variables. 
#
# See scripts/Makefile.test_mods.
#

# Examples

obj-m += liblcd_test/
obj-m += load/
obj-m += ipc1/
obj-m += ipc2/
obj-m += async/
obj-m += create_klcd/
obj-m += glue_example/
obj-m += string_example/
obj-m += pmfs/
obj-m += bug/
obj-m += async_rpc/
