#
# LCD microkernel build
#
# This is included in the top-level Makefile, and some
# variables are defined there.
#

MICROKERNEL_BUILD_DIR=$(LCD_BUILD_DIR)/microkernel_build
export MICROKERNEL_BUILD_DIR

MICROKERNEL_BASE_CFLAGS= \
	$(LCD_DOMAINS_CFLAGS) \
	-I$(LCD_DOMAINS_TOP_SRC_DIR)/include \
	-I$(LCD_DOMAINS_TOP_SRC_DIR)/arch/$(ARCH)/include \
	-I$(LCD_DOMAINS_TOP_SRC_DIR)/config/non_isolated \
	-DLINUX_KERNEL_MODULE \
	-DVMFUNC_PAGE_REMAP \
	-DOTHER_DOMAIN=1 \
	-DCONFIG_LVD \
	-DCONFIG_DEFEAT_LAZY_TLB \
	-DCONFIG_MAP_TRACE_BUFFER_BFLANK
#	-DCONFIG_LVD_PROTECT_FPU

MICROKERNEL_CFLAGS= \
	$(MICROKERNEL_BASE_CFLAGS) \
	-I$(MICROKERNEL_BUILD_DIR)/libcap.install/include \

export MICROKERNEL_CFLAGS

MICROKERNEL_DIRS= \
	microkernel \
	kliblcd \
	libcap.build \
	libcap.install \
	common \
	arch/$(ARCH)/microkernel
MICROKERNEL_BUILD_DIRS=$(foreach dir,$(MICROKERNEL_DIRS),\
	$(MICROKERNEL_BUILD_DIR)/$(dir))

MICROKERNEL_LIB_CFLAGS= $(MICROKERNEL_BASE_CFLAGS)

MICROKERNEL_LIBCAP=$(MICROKERNEL_BUILD_DIR)/libcap.install/lib/libcap.a

microkernel: $(MICROKERNEL_BUILD_DIR)/Kbuild | \
	$(MICROKERNEL_LIBCAP) \
	$(MICROKERNEL_BUILD_DIRS)
	$(MAKE) -C .. M=$(MICROKERNEL_BUILD_DIR) $(MAKEFLAGS)

libcap.microkernel: $(MICROKERNEL_BUILD_DIR)/libcap.build/Makefile
	$(MAKE) -C $(MICROKERNEL_BUILD_DIR)/libcap.build \
		CFLAGS="$(MICROKERNEL_LIB_CFLAGS)" $(MAKEFLAGS) && \
	$(MAKE) -C $(MICROKERNEL_BUILD_DIR)/libcap.build install \
	$(MAKEFLAGS) && \
	cd $(MICROKERNEL_BUILD_DIR)/libcap.install/lib && \
	ar x libcap.a

$(MICROKERNEL_BUILD_DIR)/libcap.build/Makefile: libcap/configure | \
	$(MICROKERNEL_BUILD_DIRS)
	cd $(MICROKERNEL_BUILD_DIR)/libcap.build && \
	$(LCD_DOMAINS_TOP_SRC_DIR)/libcap/configure \
	PLATFORM=kernel --disable-test-build \
	--disable-global-cap-types \
	--with-kernel-headers=$(LCD_DOMAINS_TOP_SRC_DIR)/.. \
	--disable-kernel-module \
	--prefix=$(MICROKERNEL_BUILD_DIR)/libcap.install \
	CSPACE_DEPTH_BITS=$(LCD_CSPACE_DEPTH_BITS) \
	CSPACE_CNODE_TABLE_BITS=$(LCD_CSPACE_CNODE_TABLE_BITS)

$(MICROKERNEL_BUILD_DIR)/Kbuild: scripts/Kbuild.microkernel | \
	$(MICROKERNEL_BUILD_DIRS)
	cp scripts/Kbuild.microkernel $(MICROKERNEL_BUILD_DIR)/Kbuild

$(MICROKERNEL_BUILD_DIRS):
	@echo "  MKDIR      $@"
	@mkdir -p $@

clean-microkernel: clean-mk-libcap
	if test -e $(MICROKERNEL_BUILD_DIR)/Kbuild; then \
		$(MAKE) -C .. M=$(MICROKERNEL_BUILD_DIR) clean; \
	fi

clean-mk-lib%:
	if test -d $(MICROKERNEL_BUILD_DIR)/$(subst clean-mk-,,$@).build; then \
		$(MAKE) -C $(MICROKERNEL_BUILD_DIR)/$(subst clean-mk-,,$@).build clean; \
	fi
	rm -rf $(MICROKERNEL_BUILD_DIR)/$(subst clean-mk-,,$@).install

clean: clean-microkernel

.PHONY: \
	microkernel \
	libcap.microkernel \
	clean-microkernel
