
# Main targets
obj-$(CONFIG_LCD_TEST_MOD_LIBLCD_TESTS_BOOT) += lcd-test-mod-liblcd-tests-boot.o

lcd-test-mod-liblcd-tests-boot-y             += boot.o

obj-$(CONFIG_LCD_TEST_MOD_LIBLCD_TESTS_LCD)  += lcd-test-mod-liblcd-tests-lcd.o

lcd-test-mod-liblcd-tests-lcd-y              += lcd.o

lcd-test-mod-liblcd-tests-lcd-y              += $(LIBLCD)

