#
# Modules for testing
#

export LIBLCD = ../../../../liblcd/lib.a

obj-$(CONFIG_LCD_TEST_MOD_LOAD)         += load/

obj-$(CONFIG_LCD_TEST_MOD_IPC1)         += ipc1/

obj-$(CONFIG_LCD_TEST_MOD_IPC2)         += ipc2/

obj-$(CONFIG_LCD_TEST_MOD_LIBLCD_TESTS) += liblcd-tests/

obj-$(CONFIG_LCD_TEST_MOD_CREATE_KLCD)  += create-klcd/
