
obj-m  += lcd_test_mod_async_lcd.o

lcd_test_mod_async_lcd-y              += lcd.o

lcd_test_mod_async_lcd-$(LCD_CONFIG_ASYNC_LCD_ISOLATED) += $(LIBLCD)

ccflags-$(LCD_CONFIG_ASYNC_LCD_ISOLATED) += $(ISOLATED_CFLAGS)