obj-m += lcd_test_mod_pmfs_vfs.o

# Dispatch loop, etc.
lcd_test_mod_pmfs_vfs-y              += main.o

# Glue
lcd_test_mod_pmfs_vfs-y              += $(addprefix glue/, vfs_callee.o \
							   bdi_callee.o)
