
lib-y    +=  $(addprefix lcd/, cap.o enterexit.o ipc.o page_alloc.o printk.o \
				dstore.o tests.o)

lib-y    +=  $(addprefix lib/, find_next_bit.o kstrtox.o string.o \
			       vsprintf.o ctype.o hexdump.o       \
			       reciprocal_div.o)

lib-y    +=  $(addprefix mm/, slab.o slab_common.o util.o)

lib-y    +=  resolve.o
