
ccflags-y += $(ISOLATED_CFLAGS)
ccflags-y += -DOTHER_DOMAIN=0
asflags-y += $(ISOLATED_ASFLAGS)

obj-m  += lcd_test_mod_vmfunc_klcd_callee_lcd.o

lcd_test_mod_vmfunc_klcd_callee_lcd-y              += main.o dispatch.o marshal_callee.o marshal_union_callee.o

lcd_test_mod_vmfunc_klcd_callee_lcd-y += $(LIBLCD)


extra-y += ../../../liblcd_build/common/vmfunc.lds

ldflags-y += -T $(LIBLCD_BUILD_DIR)/common/vmfunc.lds
