
obj-m  += lcd_test_mod_vmfunc_klcd_callee_lcd.o

lcd_test_mod_vmfunc_klcd_callee_lcd-y              += main.o
lcd_test_mod_vmfunc_klcd_callee_lcd-y              += $(addprefix ../, vmfunc.o vmfunc_wrapper.o)

lcd_test_mod_vmfunc_klcd_callee_lcd-y += $(LIBLCD)

ccflags-y += $(ISOLATED_CFLAGS)

extra-y += ../vmfunc.lds

ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/vmfunc_klcd/vmfunc.lds
