
# MINIX --------------------------------------------------

obj-m += lcd_test_mod_glue_example_minix.o

# original code
lcd_test_mod_glue_example_minix-y    += original/main.o

# if we're isolating ...

# link with liblcd
lcd_test_mod_glue_example_minix-$(CONFIG_ISOLATE_GLUE_EXAMPLE) += ../$(LIBLCD)

# link with glue
lcd_test_mod_glue_example_minix-$(CONFIG_ISOLATE_GLUE_EXAMPLE) += glue/boot.o
lcd_test_mod_glue_example_minix-$(CONFIG_ISOLATE_GLUE_EXAMPLE) += glue/vfs_caller.o

