
# MINIX --------------------------------------------------

obj-m += lcd_test_mod_glue_example_minix.o

# original code
lcd_test_mod_glue_example_minix-y    += original/main.o

# if we're isolating ...
ifeq ($(ISOLATE_GLUE_EXAMPLE),y)

	# link with liblcd
	lcd_test_mod_glue_example_minix-y += $(LIBLCD)

	# link with glue
	lcd_test_mod_glue_example_minix-y += glue/boot.o
	lcd_test_mod_glue_example_minix-y += glue/vfs_caller.o
	lcd_test_mod_glue_example_minix-y += glue/vfs_cap.o

	ccflags-y += $(ISOLATED_CC_FLAGS)

else

	ccflags-y += $(NON_ISOLATED_CC_FLAGS)

endif
