
# MINIX --------------------------------------------------

obj-m += lcd_test_mod_glue_example_minix.o

# original code
lcd_test_mod_glue_example_minix-y    += original/main.o

# if we're isolating ...

# link with liblcd
lcd_test_mod_glue_example_minix-$(ISOLATE_GLUE_EXAMPLE) += $(LIBLCD)

# link with glue
lcd_test_mod_glue_example_minix-$(ISOLATE_GLUE_EXAMPLE) += glue/boot.o
lcd_test_mod_glue_example_minix-$(ISOLATE_GLUE_EXAMPLE) += glue/vfs_caller.o

ifeq($ISOLATE_GLUE_EXAMPLE,m)
    ccflags-y += $(ISOLATED_CC_FLAGS)
else
    ccflags-y += $(NON_ISOLATED_CC_FLAGS)
endif

