obj-m += lcd_test_mod_msr_gen_msr_klcd.o

lcd_test_mod_msr_gen_msr_klcd-y		+= main.o
lcd_test_mod_msr_gen_msr_klcd-y		+= $(addprefix ../, server.o common.o glue_user.o)

cppflags-y += $(NONISOLATED_CFLAGS)

extra-y += $(addprefix ../, trampolines.lds)
ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/msr_gen/trampolines.lds


ccflags-y += $(NONISOLATED_CFLAGS)
