obj-m += lcd_test_mod_acpi_hwmon_vmfunc_hwmon_klcd.o

lcd_test_mod_acpi_hwmon_vmfunc_hwmon_klcd-y		+= main.o

# glue code
lcd_test_mod_acpi_hwmon_vmfunc_hwmon_klcd-y		+= $(addprefix glue/, acpi_hwmon_callee.o \
								acpi_hwmon_callee_dispatch.o )

lcd_test_mod_acpi_hwmon_vmfunc_hwmon_klcd-y		+= $(addprefix ../, acpi_hwmon_glue_helper.o)

cppflags-y += $(NONISOLATED_CFLAGS)

#extra-y += glue/acpi_hwmon_callee.lds

#ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/acpi_hwmon_vmfunc/hwmon_klcd/glue/acpi_hwmon_callee.lds

ccflags-y += $(NONISOLATED_CFLAGS)
