obj-m += lcd_test_mod_nullblk_gen_nullblk_lcd.o

lcd_test_mod_nullblk_gen_nullblk_lcd-y		+= main.o

# Original code
lcd_test_mod_nullblk_gen_nullblk_lcd-y		+= null_blk.o


lcd_test_mod_nullblk_gen_nullblk_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_nullblk_gen_nullblk_lcd-y		+= $(addprefix ../, client.o common.o glue_user.o)

ccflags-y += $(ISOLATED_CFLAGS)

extra-y += ../../../liblcd_build/common/vmfunc.lds

ldflags-y += -T $(LIBLCD_BUILD_DIR)/common/vmfunc.lds

cppflags-y += $(ISOLATED_CFLAGS)
