
# Main targets
obj-$(CONFIG_LCD_TEST_MOD_MM_BOOT)   += lcd-test-mod-mm-boot.o

lcd-test-mod-mm-boot-y               += boot.o

obj-$(CONFIG_LCD_TEST_MOD_MM_LCD)    += lcd-test-mod-mm-lcd.o

lcd-test-mod-mm-lcd-y                += lcd.o

lcd-test-mod-mm-lcd-y                += $(LIBLCD)

