
# Main targets
obj-$(CONFIG_LCD_TEST_MOD_IPC1_BOOT) += lcd-test-mod-ipc1-boot.o

lcd-test-mod-ipc1-boot-y             += boot.o

obj-$(CONFIG_LCD_TEST_MOD_IPC1_LCD)  += lcd-test-mod-ipc1-lcd.o

lcd-test-mod-ipc1-lcd-y              += lcd.o
