obj-m += lcd_test_mod_coretemp_hwmon_coretemp_lcd.o

lcd_test_mod_coretemp_hwmon_coretemp_lcd-y		+= main.o

# Original code
lcd_test_mod_coretemp_hwmon_coretemp_lcd-y		+= coretemp.o


lcd_test_mod_coretemp_hwmon_coretemp_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_coretemp_hwmon_coretemp_lcd-y		+= $(addprefix glue/, coretemp_hwmon_caller.o \
						coretemp_hwmon_caller_dispatch.o )

lcd_test_mod_coretemp_hwmon_coretemp_lcd-y		+= $(addprefix ../, coretemp_hwmon_glue_helper.o)

ccflags-y += $(ISOLATED_CFLAGS)

extra-y += ../../../liblcd_build/common/vmfunc.lds

ldflags-y += -T $(LIBLCD_BUILD_DIR)/common/vmfunc.lds
