obj-m += lcd_test_mod_skxedac_gen_edac_klcd.o

lcd_test_mod_skxedac_gen_edac_klcd-y		+= main.o

# glue code
lcd_test_mod_skxedac_gen_edac_klcd-y		+= $(addprefix ../, server.o common.o glue_user.o )

cppflags-y += $(NONISOLATED_CFLAGS)

extra-y += ../trampolines.lds

ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/skxedac_gen/trampolines.lds

ccflags-y += $(NONISOLATED_CFLAGS)

