
# Main targets
obj-m += lcd_test_mod_liblcd_tests_boot.o

lcd_test_mod_liblcd_tests_boot-y             += boot.o

obj-m  += lcd_test_mod_liblcd_tests_lcd.o

lcd_test_mod_liblcd_tests_lcd-y              += lcd.o

lcd_test_mod_liblcd_tests_lcd-y              += $(LIBLCD)

