/* 
 * syscall.h -- Syscall IDs
 *
 * Copyright: University of Utah
 */
#ifndef LCD_DOMAINS_SYSCALL_H
#define LCD_DOMAINS_SYSCALL_H

enum lcd_syscall {
	LCD_SYSCALL_CAP_DELETE,
	LCD_SYSCALL_CAP_REVOKE,
	LCD_SYSCALL_CAP_GRANT,
	LCD_SYSCALL_PUTCHAR,
	LCD_SYSCALL_CREATE,
	LCD_SYSCALL_CONFIG_REGISTERS,
	LCD_SYSCALL_MEMORY_GRANT_AND_MAP,
	LCD_SYSCALL_RUN,
	LCD_SYSCALL_EXIT,
	LCD_SYSCALL_SYNC_SEND,
	LCD_SYSCALL_SYNC_RECV,
	LCD_SYSCALL_SYNC_CALL,
	LCD_SYSCALL_SYNC_REPLY,
	LCD_SYSCALL_CREATE_SYNC_EP,
	LCD_SYSCALL_ALLOC_PAGES_EXACT_NODE,
	LCD_SYSCALL_ALLOC_PAGES,
	LCD_SYSCALL_VMALLOC,
	LCD_SYSCALL_MMAP,
	LCD_SYSCALL_MUNMAP,
};

#endif /* LCD_DOMAINS_SYSCALL_H */
