
obj-m  += lcd_test_mod_vmfunc_caller_lcd.o

lcd_test_mod_vmfunc_caller_lcd-y              += main.o

lcd_test_mod_vmfunc_caller_lcd-y += $(LIBLCD)

ccflags-y += $(ISOLATED_CFLAGS)

extra-y += ../../../liblcd_build/common/vmfunc.lds

ldflags-y += -T $(LIBLCD_BUILD_DIR)/common/vmfunc.lds
