
# Main targets
obj-$(CONFIG_LCD_TEST_MOD_IPC2_BOOT)  += lcd-test-mod-ipc2-boot.o

lcd-test-mod-ipc2-boot-y              += boot.o

obj-$(CONFIG_LCD_TEST_MOD_IPC2_LCD1)  += lcd-test-mod-ipc2-lcd1.o

lcd-test-mod-ipc2-lcd1-y              += lcd1.o

obj-$(CONFIG_LCD_TEST_MOD_IPC2_LCD2)  += lcd-test-mod-ipc2-lcd2.o

lcd-test-mod-ipc2-lcd2-y              += lcd2.o
