
# Main targets
obj-m += lcd_test_mod_create_klcd_boot.o

lcd_test_mod_create_klcd_boot-y             += boot.o

obj-m += lcd_test_mod_create_klcd_klcd.o

lcd_test_mod_create_klcd_klcd-y             += klcd.o

